# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import stream_pb2 as proto_dot_stream__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/stream_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class StreamServiceStub(object):
    """サービス定定義
    Bidirectional Streaming RPC (双方向ストリーミング)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.BidirectionalStream = channel.stream_stream(
                '/stream.StreamService/BidirectionalStream',
                request_serializer=proto_dot_stream__pb2.Request.SerializeToString,
                response_deserializer=proto_dot_stream__pb2.Response.FromString,
                _registered_method=True)


class StreamServiceServicer(object):
    """サービス定定義
    Bidirectional Streaming RPC (双方向ストリーミング)
    """

    def BidirectionalStream(self, request_iterator, context):
        """クライアントとサーバーが互いにストリームでデータを送受信します。
        `stream` キーワードが両方の引数と戻り値についているのが特徴です。
        クライアントは任意のタイミングでRequestを送り、サーバーも任意のタイミングでResponseを返せます。
        TCPのような全二重通信が可能です。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StreamServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'BidirectionalStream': grpc.stream_stream_rpc_method_handler(
                    servicer.BidirectionalStream,
                    request_deserializer=proto_dot_stream__pb2.Request.FromString,
                    response_serializer=proto_dot_stream__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'stream.StreamService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('stream.StreamService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StreamService(object):
    """サービス定定義
    Bidirectional Streaming RPC (双方向ストリーミング)
    """

    @staticmethod
    def BidirectionalStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/stream.StreamService/BidirectionalStream',
            proto_dot_stream__pb2.Request.SerializeToString,
            proto_dot_stream__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
